from pathlib import Path

"""Configuration for the first SAM 3 text-guided tracking stage.

Run one physical GPU at a time:
    CUDA_VISIBLE_DEVICES=<physical_gpu_id> python scripts/run_sam3_tracking.py

The first run is intentionally one visible GPU / one resident predictor / one
video at a time. After output parsing and memory behavior are verified, this
same adapter will be extended to multiple independent workers per GPU.
"""

PROJECT_ROOT = Path("/input/workflow_58770161/workspace/test/cameramotion_det")
RES_ROOT = PROJECT_ROOT / "res"

# Input generated by scripts/run_qwen_object_proposals.py. This SAM stage expects
# qwen_region_candidates_v3-style structured candidate objects, not v2 bare strings.
QWEN_SAM3_CANDIDATES_PATH = (
    RES_ROOT / "qwen_region_candidates" / "qwen_sam3_candidates.json"
)

# Official code and checkpoint. This project never edits SAM3 source files.
SAM3_SOURCE_ROOT = Path("/input/workflow_58770161/workspace/test/sam3-main")
SAM3_CHECKPOINT_PATH = Path("/home/admin/sam3/sam3.pt")

# Small aggregate metadata.
SAM3_RESULT_ROOT = RES_ROOT / "sam_focus_regions"
SAM3_TRACKS_ALL_PATH = SAM3_RESULT_ROOT / "sam3_tracks_all.json"
SAM3_FOCUS_REGIONS_PATH = SAM3_RESULT_ROOT / "sam3_focus_regions.json"
SAM3_FAILURES_PATH = SAM3_RESULT_ROOT / "sam3_failures.json"
SAM3_RUN_SUMMARY_PATH = SAM3_RESULT_ROOT / "sam3_run_summary.json"

# Large mask tubes. Only final focus masks are retained permanently. Candidate
# track masks are temporary and removed after focus selection for each video.
SAM3_LARGE_OUTPUT_ROOT = Path("/tmp/cambench_train/cam_train/object_discovery_sam")
SAM3_FOCUS_MASK_ROOT = SAM3_LARGE_OUTPUT_ROOT / "focus_masks"
SAM3_WORK_MASK_ROOT = SAM3_LARGE_OUTPUT_ROOT / "_work"

# ---------------------------------------------------------------------------
# Runtime: choose physical card at shell level, then this process sees it as 0.
# ---------------------------------------------------------------------------
SAM3_LOCAL_GPU_IDS = (0,)
SAM3_EXPECTED_VISIBLE_GPU_COUNT = 1
SAM3_COMPILE = False
SAM3_ASYNC_LOADING_FRAMES = False
SAM3_VIDEO_LOADER_TYPE = "cv2"
SAM3_OFFLOAD_VIDEO_TO_CPU = False
SAM3_OFFLOAD_STATE_TO_CPU = False
SAM3_APPLY_TEMPORAL_DISAMBIGUATION = True

# Prompt / propagation policy.
SAM3_PROMPT_FRAME_INDEX = 0
SAM3_PROPAGATION_DIRECTION = "forward"
SAM3_OUTPUT_PROB_THRESH = 0.50
SAM3_MAX_CANDIDATES_PER_VIDEO = 6

# Result persistence and smoke-test control.
SAM3_SCHEMA_VERSION = "sam3_focus_tracking_v1"
SAM3_MAX_VIDEOS = 1
SAM3_SHUFFLE_INPUT = False
SAM3_OVERWRITE_EXISTING = False
SAM3_RETRY_FAILURE_RECORDS = True
SAM3_SAVE_EVERY = 1
SAM3_PROGRESS_EVERY = 1

# Official SAM3 close_session conditionally clears allocator cache above this
# reserved-memory percentage. Keep model weights resident between videos.
SAM3_CLOSE_SESSION_RUN_GC = True
SAM3_CLEAR_CACHE_THRESHOLD = 80

# First-pass eligibility. Inspect the first video before tightening thresholds.
SAM3_MIN_VISIBLE_FRAME_RATIO = 0.20
SAM3_MIN_LONGEST_VISIBLE_RUN = 8
SAM3_MIN_MEDIAN_AREA_RATIO = 0.002
SAM3_MAX_MEDIAN_AREA_RATIO = 0.90
SAM3_MAX_BORDER_TOUCH_RATIO = 0.95

# Focus selection is within a video only. The Qwen priority contributes a small
# tie-break signal; region_family does not force a route or a winner.
SAM3_SCORE_WEIGHTS = {
    "visible_frame_ratio": 0.28,
    "longest_run_ratio": 0.17,
    "area_quality": 0.16,
    "area_stability": 0.12,
    "interior_ratio": 0.08,
    "mean_detection_score": 0.08,
    "screen_region_match": 0.06,
    "qwen_priority": 0.05,
}
